/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResultJobIdRouteImport } from './routes/result.$jobId'
import { Route as GenerateJobIdRouteImport } from './routes/generate.$jobId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultJobIdRoute = ResultJobIdRouteImport.update({
  id: '/result/$jobId',
  path: '/result/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateJobIdRoute = GenerateJobIdRouteImport.update({
  id: '/generate/$jobId',
  path: '/generate/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/generate/$jobId': typeof GenerateJobIdRoute
  '/result/$jobId': typeof ResultJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/generate/$jobId': typeof GenerateJobIdRoute
  '/result/$jobId': typeof ResultJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/generate/$jobId': typeof GenerateJobIdRoute
  '/result/$jobId': typeof ResultJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/generate/$jobId' | '/result/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/generate/$jobId' | '/result/$jobId'
  id: '__root__' | '/' | '/auth' | '/generate/$jobId' | '/result/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  GenerateJobIdRoute: typeof GenerateJobIdRoute
  ResultJobIdRoute: typeof ResultJobIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result/$jobId': {
      id: '/result/$jobId'
      path: '/result/$jobId'
      fullPath: '/result/$jobId'
      preLoaderRoute: typeof ResultJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate/$jobId': {
      id: '/generate/$jobId'
      path: '/generate/$jobId'
      fullPath: '/generate/$jobId'
      preLoaderRoute: typeof GenerateJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  GenerateJobIdRoute: GenerateJobIdRoute,
  ResultJobIdRoute: ResultJobIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
